import {useEffect,useMemo,useState} from "react";
import {ExternalLink,RefreshCw,ShieldCheck} from "lucide-react";
import {api} from "../api";
import {useAuth} from "../context/AuthContext";
import {useWorkspace} from "../context/WorkspaceContext";

const metrics=[["Views","views"],["Reach","reach"],["Total interactions","totalInteractions"],["Likes","likes"],["Comments","comments"],["Saves","saves"],["Shares","shares"]];
const statusStyles={APPROVED:"bg-emerald-200",REQUESTED:"bg-sky-100",DECLINED:"bg-red-100",REVOKED:"bg-zinc-200",EXPIRED:"bg-amber-100",NOT_REQUESTED:"bg-white"};
const formatter=new Intl.NumberFormat();
const numeric=value=>Number.isFinite(Number(value))?Number(value):0;
const format=value=>formatter.format(numeric(value));
const timestamp=value=>{if(!value)return "No snapshot yet";const parsed=new Date(value);return Number.isNaN(parsed.getTime())?"Date unavailable":parsed.toLocaleString()};
const calendar=value=>{if(!value)return null;const parsed=new Date(`${value}T00:00:00`);return Number.isNaN(parsed.getTime())?null:parsed.toLocaleDateString()};
const engagement=totals=>numeric(totals?.reach)>0?numeric(totals?.totalInteractions)/numeric(totals?.reach)*100:numeric(totals?.engagementRate);

function MetricCards({totals={},compact=false}){
 return <div className={`grid gap-3 ${compact?"grid-cols-2 sm:grid-cols-4":"sm:grid-cols-2 xl:grid-cols-4"}`}>{metrics.map(([label,key])=><article key={key} className="border-2 border-zinc-900 bg-white p-4 shadow-[3px_3px_0_#18181b]"><p className="text-[10px] font-black uppercase tracking-wider text-zinc-500">{label}</p><p className={`mt-2 font-mono font-black ${compact?"text-lg":"text-2xl"}`}>{format(totals[key])}</p></article>)}<article className="border-2 border-zinc-900 bg-yellow-300 p-4 shadow-[3px_3px_0_#18181b]"><p className="text-[10px] font-black uppercase tracking-wider">Engagement / reach</p><p className={`mt-2 font-mono font-black ${compact?"text-lg":"text-2xl"}`}>{engagement(totals).toFixed(2)}%</p></article></div>;
}

function CountCards({summary={}}){
 const items=[["Participating creators",summary.creatorCount],["Creators sharing",summary.sharedCreatorCount],["Approved",summary.approvedDeliverableCount],["Awaiting approval",summary.pendingDeliverableCount],["Declined",summary.declinedDeliverableCount],["Revoked",summary.revokedDeliverableCount],["Expired",summary.expiredDeliverableCount]];
 return <div className="grid grid-cols-2 gap-3 sm:grid-cols-4 xl:grid-cols-7">{items.map(([label,value])=><div key={label} className="border-2 border-zinc-900 bg-white p-3"><p className="text-[9px] font-black uppercase text-zinc-500">{label}</p><p className="mt-1 font-mono text-xl font-black">{format(value)}</p></div>)}</div>;
}

function CampaignSelector({campaigns,selectedId,onSelect}){
 return <section aria-labelledby="campaign-selector-title"><p className="brutal-overline">Campaign selector</p><h2 id="campaign-selector-title" className="mb-4 mt-2 text-2xl font-black">Choose a campaign</h2><div className="grid gap-4 lg:grid-cols-3">{campaigns.map(item=>{const start=calendar(item.startDate),end=calendar(item.endDate);return <button key={item.campaignId} type="button" onClick={()=>onSelect(item.campaignId)} aria-pressed={selectedId===item.campaignId} className={`text-left border-2 border-zinc-900 p-5 transition-transform ${selectedId===item.campaignId?"bg-yellow-300 shadow-[5px_5px_0_#18181b]":"bg-white hover:-translate-y-0.5"}`}><div className="flex justify-between gap-3"><h3 className="break-words text-lg font-black">{item.campaignName||"Untitled campaign"}</h3><span className="h-fit border border-zinc-900 bg-white px-2 py-1 text-[9px] font-black">{item.campaignStatus||"UNKNOWN"}</span></div>{(start||end)&&<p className="mt-2 text-xs text-zinc-600">{start||"No start"} – {end||"No end"}</p>}<dl className="mt-5 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-zinc-500">Approved deliverables</dt><dd className="font-bold">{format(item.approvedDeliverableCount)}</dd></div><div><dt className="text-zinc-500">Awaiting approval</dt><dd className="font-bold">{format(item.pendingDeliverableCount)}</dd></div><div><dt className="text-zinc-500">Shared creators</dt><dd className="font-bold">{format(item.sharedCreatorCount)} / {format(item.creatorCount)}</dd></div><div><dt className="text-zinc-500">Total views</dt><dd className="font-bold">{format(item.totals?.views)}</dd></div><div><dt className="text-zinc-500">Total reach</dt><dd className="font-bold">{format(item.totals?.reach)}</dd></div></dl><p className="mt-4 border-t border-zinc-900 pt-3 text-[11px] text-zinc-600">Latest snapshot: {timestamp(item.lastCapturedAt)}</p></button>})}</div></section>;
}

function DeliverableAnalytics({item}){
 const status=item.shareStatus||"NOT_REQUESTED",approved=status==="APPROVED",showMetrics=approved&&item.metrics;
 return <div className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><strong>{item.deliverableType||"Deliverable"}</strong><span className={`border border-zinc-900 px-2 py-0.5 text-[10px] font-black ${statusStyles[status]||"bg-white"}`}>{status.replaceAll("_"," ")}</span></div><p className="mt-1 text-xs text-zinc-500">Snapshot: {approved?timestamp(item.capturedAt):"No active approved snapshot"}</p>{item.expiresAt&&<p className="mt-1 text-xs text-zinc-500">Access expires: {timestamp(item.expiresAt)}</p>}</div>{(item.permalink||item.publishedUrl)&&<a href={item.permalink||item.publishedUrl} target="_blank" rel="noopener noreferrer" className="flex items-center gap-1 text-xs font-black underline">View Instagram content <ExternalLink size={13}/></a>}</div>{showMetrics?<div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-8">{metrics.map(([label,key])=><div key={key} className="border border-zinc-300 p-2"><p className="text-[9px] uppercase text-zinc-500">{label}</p><strong className="font-mono text-sm">{format(item.metrics[key])}</strong></div>)}<div className="border border-zinc-300 bg-yellow-100 p-2"><p className="text-[9px] uppercase">Engagement</p><strong className="font-mono text-sm">{engagement(item.metrics).toFixed(2)}%</strong></div></div>:<p className="mt-4 border border-zinc-300 bg-zinc-50 p-3 text-sm text-zinc-600">Metrics require an active creator-approved share. No performance values from this deliverable are displayed or inferred.</p>}</div>;
}

function CampaignDetail({detail}){
 const summary=detail.summary||{},creators=Array.isArray(detail.creators)?detail.creators:[],hasRequests=numeric(summary.deliverableCount)>0,hasApprovals=numeric(summary.approvedDeliverableCount)>0;
 return <section className="space-y-6"><div className="border-b-2 border-zinc-900 pb-4"><p className="brutal-overline">Selected campaign</p><div className="mt-2 flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-3xl font-black">{summary.campaignName||"Campaign analytics"}</h2><p className="mt-2 text-sm text-zinc-600">Latest snapshot: {timestamp(summary.lastCapturedAt)}</p></div><span className="border-2 border-zinc-900 bg-white px-3 py-2 text-xs font-black">{summary.campaignStatus||"UNKNOWN"}</span></div></div><CountCards summary={summary}/><MetricCards totals={summary.totals}/>{!hasRequests?<div className="brutal-card p-10 text-center"><h3 className="text-xl font-black">No insight requests yet</h3><p className="mt-2 text-zinc-600">Request insight sharing from a campaign deliverable to begin collecting creator-approved snapshots.</p></div>:!hasApprovals?<div className="brutal-card p-10 text-center"><h3 className="text-xl font-black">No approved insight shares yet</h3><p className="mt-2 text-zinc-600">Requests exist, but analytics remain private until creators approve sharing for individual deliverables.</p></div>:null}{creators.length>0&&<div className="space-y-5">{creators.map((creator,index)=>{const deliverables=Array.isArray(creator.deliverables)?creator.deliverables:[];return <article key={creator.creatorProfileId||index} className="brutal-card overflow-hidden"><header className="flex flex-wrap items-center justify-between gap-4 border-b-2 border-zinc-900 bg-sky-100 p-5"><div className="flex items-center gap-3">{creator.profilePictureUrl?<img src={creator.profilePictureUrl} alt={`@${creator.instagramUsername||"creator"} profile`} className="h-12 w-12 border-2 border-zinc-900 object-cover"/>:<span className="flex h-12 w-12 items-center justify-center border-2 border-zinc-900 bg-white font-black">{creator.instagramUsername?.[0]?.toUpperCase()||"?"}</span>}<div><h3 className="text-xl font-black">@{creator.instagramUsername||"creator"}</h3><p className="text-xs text-zinc-600">{format(creator.approvedDeliverableCount)} approved deliverables · Last captured {timestamp(creator.lastCapturedAt)}</p></div></div></header><div className="border-b-2 border-zinc-900 bg-zinc-50 p-4"><MetricCards totals={creator.totals} compact/></div>{deliverables.length?<div className="divide-y-2 divide-zinc-900">{deliverables.map((item,itemIndex)=><DeliverableAnalytics key={item.deliverableId||itemIndex} item={item}/>)}</div>:<p className="p-5 text-sm text-zinc-600">No deliverable insight requests are available for this creator.</p>}</article>})}</div>}</section>;
}

export default function BrandAnalytics(){
 const {token,logout}=useAuth(),{selectedWorkspaceId,selectedWorkspace,reloadWorkspaces,loading:workspaceLoading}=useWorkspace();
 const [campaigns,setCampaigns]=useState([]),[selectedId,setSelectedId]=useState(""),[detail,setDetail]=useState(null),[loading,setLoading]=useState(false),[detailLoading,setDetailLoading]=useState(false),[error,setError]=useState(""),[refreshVersion,setRefreshVersion]=useState(0);
 useEffect(()=>{setCampaigns([]);setSelectedId("");setDetail(null);setError("");if(!selectedWorkspaceId)return;const controller=new AbortController();setLoading(true);api.listCampaignAnalytics(selectedWorkspaceId,token,{signal:controller.signal}).then(result=>{const items=Array.isArray(result)?result:[];setCampaigns(items);setSelectedId(current=>items.some(item=>item.campaignId===current)?current:items[0]?.campaignId||"")}).catch(err=>{if(err.name==="AbortError")return;if(err.status===401)logout();else if(err.status===403){setError("You cannot view analytics in this workspace.");reloadWorkspaces()}else setError(err.status>=500?"Campaign analytics are temporarily unavailable.":err.message)}).finally(()=>!controller.signal.aborted&&setLoading(false));return()=>controller.abort()},[selectedWorkspaceId,token,refreshVersion]);
 useEffect(()=>{setDetail(null);if(!selectedWorkspaceId||!selectedId)return;const controller=new AbortController();setDetailLoading(true);api.getCampaignAnalytics(selectedWorkspaceId,selectedId,token,{signal:controller.signal}).then(setDetail).catch(err=>{if(err.name==="AbortError")return;if(err.status===401)logout();else if(err.status===403){setError("You cannot view analytics in this workspace.");reloadWorkspaces()}else if(err.status===404){setError("That campaign no longer exists. Campaign analytics were refreshed.");setSelectedId("");setRefreshVersion(value=>value+1)}else setError(err.status>=500?"Campaign analytics are temporarily unavailable.":err.message)}).finally(()=>!controller.signal.aborted&&setDetailLoading(false));return()=>controller.abort()},[selectedWorkspaceId,selectedId,token,refreshVersion]);
 const workspaceTotals=useMemo(()=>{const totals={};for(const campaign of campaigns)for(const [,key] of metrics)totals[key]=numeric(totals[key])+numeric(campaign.totals?.[key]);totals.engagementRate=numeric(totals.reach)>0?numeric(totals.totalInteractions)/numeric(totals.reach)*100:0;return totals},[campaigns]);
 const refreshing=loading||detailLoading;
 return <main className="brutal-page min-h-[calc(100vh-82px)] p-4 sm:p-6 md:p-8"><div className="mx-auto max-w-7xl space-y-7"><header className="border-b-2 border-zinc-900 pb-6"><p className="brutal-overline">{selectedWorkspace?.name||"Brand / Agency workspace"}</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-4xl font-black">Campaign Analytics</h1><p className="mt-2 max-w-3xl text-zinc-600">Performance from the latest creator-approved snapshot for each deliverable—not live or account-wide Creator analytics.</p></div><button type="button" onClick={()=>setRefreshVersion(value=>value+1)} disabled={refreshing||!selectedWorkspaceId} className="brutal-button flex gap-2 px-4 py-2 text-sm"><RefreshCw size={16} className={refreshing?"animate-spin":""}/>{refreshing?"Refreshing…":"Refresh analytics"}</button></div><div className="mt-5 flex gap-3 border-2 border-zinc-900 bg-emerald-100 p-4 text-sm"><ShieldCheck className="shrink-0"/><p><strong>Privacy-safe reporting:</strong> revoked and expired shares are excluded, and multiple historical snapshots are never added together.</p></div></header>{error&&<div role="alert" className="border-2 border-red-700 bg-red-50 p-4 font-bold text-red-800">{error}</div>}{workspaceLoading||loading?<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[1,2,3,4,5,6,7,8].map(item=><div key={item} className="h-28 animate-pulse border-2 border-zinc-900 bg-zinc-200"/>)}</div>:!selectedWorkspaceId?<div className="brutal-card p-10 text-center">Select a Brand or Agency workspace to view analytics.</div>:!campaigns.length?<div className="brutal-card p-10 text-center"><h2 className="text-2xl font-black">No campaigns yet</h2><p className="mt-2 text-zinc-600">Create a campaign and request deliverable insights to begin tracking performance.</p></div>:<><section><p className="brutal-overline">Workspace performance</p><h2 className="mb-4 mt-2 text-2xl font-black">Across {campaigns.length} campaign{campaigns.length===1?"":"s"}</h2><MetricCards totals={workspaceTotals}/></section><CampaignSelector campaigns={campaigns} selectedId={selectedId} onSelect={setSelectedId}/>{detailLoading?<div className="space-y-4" aria-label="Loading campaign details"><div className="h-24 animate-pulse border-2 border-zinc-900 bg-zinc-200"/><div className="h-80 animate-pulse border-2 border-zinc-900 bg-zinc-200"/></div>:detail&&<CampaignDetail detail={detail}/>}</>}</div></main>;
}
