import { useEffect, useMemo, useRef, useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import { useWorkspace } from "../context/WorkspaceContext";
import { campaignService } from "../services/campaignService";
import CampaignForm from "../components/CampaignForm";
import { useWorkspaceAuthorization } from "../context/WorkspaceAuthorizationContext";

const STATUS_STYLE = { DRAFT:"bg-slate-500/10 text-slate-300", ACTIVE:"bg-emerald-500/10 text-emerald-300", PAUSED:"bg-amber-500/10 text-amber-300", COMPLETED:"bg-indigo-500/10 text-indigo-300", CANCELLED:"bg-red-500/10 text-red-300" };
function money(campaign) { return campaign.budget != null && campaign.currency ? new Intl.NumberFormat(undefined,{style:"currency",currency:campaign.currency}).format(campaign.budget) : "No budget"; }

export default function Campaigns() {
  const { token, logout } = useAuth(); const { selectedWorkspace, selectedWorkspaceId, reloadWorkspaces } = useWorkspace(); const navigate = useNavigate(); const location = useLocation();
  const { hasPermission } = useWorkspaceAuthorization(); const canEdit=hasPermission("CAMPAIGN_EDIT");
  const saved = location.state?.campaignFilters || {};
  const [campaigns,setCampaigns]=useState([]); const [campaignsWorkspaceId,setCampaignsWorkspaceId]=useState(""); const [loading,setLoading]=useState(true); const [error,setError]=useState(null); const [query,setQuery]=useState(saved.query||""); const [status,setStatus]=useState(saved.status||""); const [formCampaign,setFormCampaign]=useState(undefined); const [formOpen,setFormOpen]=useState(false); const [submitting,setSubmitting]=useState(false); const requestId=useRef(0);
  async function load() { const id=++requestId.current; setCampaigns([]);setCampaignsWorkspaceId(""); if(!selectedWorkspaceId){setLoading(false);return} setLoading(true);setError(null);try{const result=await campaignService.list(selectedWorkspaceId,token);if(id===requestId.current){setCampaigns(Array.isArray(result)?result:[]);setCampaignsWorkspaceId(selectedWorkspaceId)}}catch(err){if(id!==requestId.current)return;if(err.status===401)logout();else if(err.status===403){setError("You cannot access this workspace.");reloadWorkspaces()}else setError(err.status>=500?"Campaigns are temporarily unavailable. Please retry.":err.message)}finally{if(id===requestId.current)setLoading(false)}}
  useEffect(()=>{setFormOpen(false);setFormCampaign(undefined);load()},[selectedWorkspaceId,token]);
  const filtered=useMemo(()=>(campaignsWorkspaceId===selectedWorkspaceId?campaigns:[]).filter(item=>(!query||item.name.toLowerCase().includes(query.toLowerCase()))&&(!status||item.status===status)),[campaigns,campaignsWorkspaceId,selectedWorkspaceId,query,status]);
  async function save(payload){if(submitting||!canEdit)return;setSubmitting(true);try{if(formCampaign){const updated=await campaignService.update(selectedWorkspaceId,formCampaign.id,payload,token);setCampaigns(c=>c.map(x=>x.id===updated.id?updated:x))}else{const created=await campaignService.create(selectedWorkspaceId,payload,token);setCampaigns(c=>[created,...c])}setFormOpen(false);setFormCampaign(undefined)}finally{setSubmitting(false)}}
  async function remove(campaign){if(!canEdit||!window.confirm(`Delete “${campaign.name}”? This cannot be undone.`))return;setSubmitting(true);try{await campaignService.delete(selectedWorkspaceId,campaign.id,token);setCampaigns(c=>c.filter(x=>x.id!==campaign.id))}catch(err){setError(err.status>=500?"The campaign could not be deleted. Please retry.":err.message)}finally{setSubmitting(false)}}
  if(!selectedWorkspace)return <div className="min-h-screen bg-bg-deep p-8 text-text-primary">
<div className="mx-auto max-w-xl rounded-3xl bg-panel p-10 text-center">
<h1 className="text-xl font-bold">Select a workspace first</h1>
<Link to="/dashboard" className="mt-5 inline-block rounded-xl bg-accent-primary px-5 py-3">Dashboard</Link>
</div>
</div>;
  return <div className="min-h-screen bg-bg-deep px-4 py-8 text-text-primary">
<div className="mx-auto max-w-7xl space-y-6">
<header className="flex flex-col gap-4 rounded-3xl border border-panel-border bg-panel/50 p-6 sm:flex-row sm:items-center sm:justify-between">
<div>
<Link to="/dashboard" className="text-xs text-text-secondary">← Dashboard</Link>
<h1 className="mt-2 text-2xl font-bold">Campaigns</h1>
<p className="mt-1 text-sm text-text-secondary">Campaigns in {selectedWorkspace.name}</p>
</div>{canEdit&&<button onClick={()=>{setFormCampaign(undefined);setFormOpen(true)}} className="rounded-xl bg-accent-primary px-5 py-3 text-sm font-semibold">Create campaign</button>}</header>{error&&<div role="alert" className="rounded-xl bg-red-500/10 p-4 text-sm text-red-300">{error}</div>}{formOpen&&<CampaignForm initial={formCampaign} submitting={submitting} onSubmit={save} onCancel={()=>setFormOpen(false)}/>}<div className="flex flex-col gap-3 rounded-2xl border border-panel-border bg-panel/40 p-4 sm:flex-row">
<label className="flex-1 text-xs text-text-secondary">Search<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Campaign name" className="mt-1 w-full rounded-xl border border-panel-border bg-bg-deep p-3 text-text-primary"/>
</label>
<label className="text-xs text-text-secondary">Status<select value={status} onChange={e=>setStatus(e.target.value)} className="mt-1 w-full rounded-xl border border-panel-border bg-bg-deep p-3 text-text-primary">
<option value="">All statuses</option>{["DRAFT","ACTIVE","PAUSED","COMPLETED","CANCELLED"].map(x=>
<option key={x}>{x}</option>)}</select>
</label>
</div>{loading||campaignsWorkspaceId!==selectedWorkspaceId?<div className="grid gap-4 md:grid-cols-2">{[1,2,3,4].map(x=><div key={x} className="h-56 animate-pulse border-2 border-zinc-900 bg-zinc-200"/>)}</div>:<CampaignGrid campaigns={filtered} canEdit={canEdit} submitting={submitting} query={query} status={status} navigate={navigate} onEdit={campaign=>{setFormCampaign(campaign);setFormOpen(true)}} onDelete={remove}/>}</div>
</div>;
}

function CampaignGrid({campaigns,canEdit,submitting,query,status,navigate,onEdit,onDelete}){if(!campaigns.length)return <div className="border-2 border-dashed border-zinc-400 p-12 text-center"><h2 className="text-xl font-black">No campaigns found</h2><p className="mt-2 text-sm text-zinc-600">Create a campaign or adjust the filters.</p></div>;return <section aria-label="Campaigns" className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{campaigns.map(campaign=><article key={campaign.id} className="brutal-card p-6"><div className="flex items-start justify-between gap-3"><h2 className="break-words text-xl font-black">{campaign.name}</h2><span className="border border-zinc-900 bg-zinc-100 px-2 py-1 text-[10px] font-black">{campaign.status}</span></div><p className="mt-3 line-clamp-2 text-sm text-zinc-600">{campaign.objective||campaign.description||"No objective"}</p><dl className="mt-5 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-xs text-zinc-500">Budget</dt><dd className="font-mono font-bold">{money(campaign)}</dd></div><div><dt className="text-xs text-zinc-500">Creators</dt><dd className="font-mono font-bold">{campaign.creatorCount||0}</dd></div><div className="col-span-2"><dt className="text-xs text-zinc-500">Campaign dates</dt><dd>{campaign.startDate||"No start"} – {campaign.endDate||"No end"}</dd></div></dl><div className="mt-4 flex flex-wrap gap-2">{(campaign.targetPlatforms||[]).map(platform=><span key={platform} className="border border-zinc-300 bg-zinc-100 px-2 py-1 text-[10px] font-bold uppercase">{platform}</span>)}</div><div className="mt-5 flex flex-wrap gap-2 border-t-2 border-zinc-900 pt-4"><button onClick={()=>navigate(`/campaigns/${campaign.id}`,{state:{campaignFilters:{query,status}}})} className="border-2 border-zinc-900 bg-yellow-300 px-4 py-2 text-xs font-black">Open</button>{canEdit&&<button onClick={()=>onEdit(campaign)} className="border-2 border-zinc-900 bg-white px-4 py-2 text-xs font-black">Edit</button>}{canEdit&&<button disabled={submitting} onClick={()=>onDelete(campaign)} className="border-2 border-red-600 bg-white px-4 py-2 text-xs font-black text-red-700">Delete</button>}</div></article>)}</section>}

const BOARD_COLUMNS=[
 {key:"ACTIVE",label:"Active",color:"bg-sky-200"},
 {key:"SCRIPTING",label:"Scripting",color:"bg-yellow-300"},
 {key:"VIDEO_REVIEW",label:"Video Review",color:"bg-rose-200"},
 {key:"LIVE",label:"Live",color:"bg-emerald-200"},
 {key:"PAYMENT",label:"Payment",color:"bg-zinc-200"},
];
function boardStage(campaign){const explicit=String(campaign.workflowStage||campaign.stage||"").toUpperCase().replace(/\s+/g,"_");if(BOARD_COLUMNS.some(column=>column.key===explicit))return explicit;if(campaign.status==="COMPLETED")return "LIVE";if(campaign.status==="PAUSED")return "SCRIPTING";if(campaign.status==="CANCELLED")return "PAYMENT";return "ACTIVE"}
function CampaignBoard({campaigns,canEdit,submitting,query,status,navigate,onEdit,onDelete}){return <section aria-label="Campaign Kanban board"><div className="overflow-x-auto pb-5"><div className="grid min-w-[1380px] grid-cols-5 gap-4">{BOARD_COLUMNS.map(column=>{const items=campaigns.filter(campaign=>boardStage(campaign)===column.key);return <section key={column.key} aria-labelledby={`campaign-column-${column.key}`} className="min-h-[430px] border-2 border-zinc-900 bg-white"><header className={`flex h-14 items-center justify-between gap-3 border-b-2 border-zinc-900 px-4 ${column.color}`}><h2 id={`campaign-column-${column.key}`} className="text-sm font-black uppercase tracking-wide">{column.label}</h2><span className="flex h-7 min-w-7 items-center justify-center rounded-full bg-zinc-900 px-2 font-mono text-xs font-black text-white">{items.length}</span></header><div className="space-y-3 p-3">{items.map(campaign=><article key={campaign.id} className="border-2 border-zinc-900 bg-white p-4 shadow-[3px_3px_0_#18181b]"><div className="flex items-start justify-between gap-2"><h3 className="break-words text-base font-black">{campaign.name}</h3><span className="border border-zinc-900 bg-zinc-100 px-2 py-1 text-[9px] font-black">{campaign.status}</span></div><p className="mt-3 line-clamp-2 text-sm text-zinc-600">{campaign.objective||campaign.description||"No objective"}</p><dl className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-zinc-500">Budget</dt><dd className="font-mono font-bold">{money(campaign)}</dd></div><div><dt className="text-zinc-500">Creators</dt><dd className="font-mono font-bold">{campaign.creatorCount||0}</dd></div><div className="col-span-2"><dt className="text-zinc-500">Dates</dt><dd>{campaign.startDate||"No start"} – {campaign.endDate||"No end"}</dd></div></dl><div className="mt-3 flex flex-wrap gap-1">{(campaign.targetPlatforms||[]).map(platform=><span key={platform} className="border border-zinc-300 bg-zinc-100 px-2 py-1 text-[9px] font-bold uppercase">{platform}</span>)}</div><div className="mt-4 flex flex-wrap gap-2 border-t-2 border-zinc-900 pt-3"><button onClick={()=>navigate(`/campaigns/${campaign.id}`,{state:{campaignFilters:{query,status}}})} className="border-2 border-zinc-900 bg-yellow-300 px-3 py-2 text-xs font-black">Open</button>{canEdit&&<button onClick={()=>onEdit(campaign)} className="border-2 border-zinc-900 bg-white px-3 py-2 text-xs font-black">Edit</button>}{canEdit&&<button disabled={submitting} onClick={()=>onDelete(campaign)} className="border-2 border-red-600 bg-white px-3 py-2 text-xs font-black text-red-700">Delete</button>}</div></article>)}{!items.length&&<p className="p-5 text-center text-xs text-zinc-400">No campaigns</p>}</div></section>})}</div></div>{!campaigns.length&&<p className="mt-2 text-center text-sm text-zinc-500">No campaigns match the current filters. Create a campaign or adjust the filters.</p>}</section>}
