import { useEffect, useState } from "react";
import { useAuth } from "../context/AuthContext";
import { useWorkspace } from "../context/WorkspaceContext";
import { campaignService } from "../services/campaignService";

export default function AddToCampaignDialog({creatorProfileId,creatorName,onClose}){
 const {token,logout}=useAuth();const {selectedWorkspaceId,reloadWorkspaces}=useWorkspace();const [campaigns,setCampaigns]=useState([]);const [campaignId,setCampaignId]=useState("");const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState(null);
 useEffect(()=>{let active=true;campaignService.list(selectedWorkspaceId,token).then(r=>{if(active){const items=Array.isArray(r)?r:[];setCampaigns(items);setCampaignId(items[0]?.id||"")}}).catch(e=>{if(!active)return;if(e.status===401)logout();else if(e.status===403){setError("You cannot access this workspace.");reloadWorkspaces()}else setError(e.status>=500?"Campaigns are temporarily unavailable.":e.message)}).finally(()=>active&&setLoading(false));return()=>{active=false}},[selectedWorkspaceId,token]);
 async function submit(e){e.preventDefault();if(saving||!campaignId)return;setSaving(true);setError(null);try{await campaignService.addCreator(selectedWorkspaceId,campaignId,{creatorProfileId,status:"INVITED",agreedCost:null,currency:null,notes:null,rejectionReason:null},token);onClose()}catch(err){setError(err.status===409?"Creator is already in this campaign.":err.status>=500?"The creator could not be added. Please retry.":err.message)}finally{setSaving(false)}}
 return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/75 p-4"><form onSubmit={submit} role="dialog" aria-modal="true" className="w-full max-w-md rounded-3xl bg-panel p-6"><h2 className="text-lg font-bold">Add to campaign</h2><p className="mt-1 text-xs text-text-secondary">{creatorName}</p>{error&&<p className="mt-4 rounded-xl bg-red-500/10 p-3 text-xs text-red-300">{error}</p>}{loading?<p className="py-8 text-center text-xs text-text-secondary">Loading campaigns…</p>:<label className="mt-5 block text-xs text-text-secondary">Campaign<select value={campaignId} onChange={e=>setCampaignId(e.target.value)} className="mt-1 w-full rounded-xl border border-panel-border bg-bg-deep p-3 text-text-primary"><option value="">Select a campaign</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}<div className="mt-5 flex gap-2"><button disabled={saving||!campaignId} className="rounded-xl bg-accent-primary px-4 py-3 text-sm disabled:opacity-50">{saving?"Adding…":"Add as invited"}</button><button type="button" onClick={onClose} className="rounded-xl border border-panel-border px-4 py-3 text-sm">Cancel</button></div></form></div>
}
