import {useEffect,useState} from "react";
import {api} from "../api";
import {useWorkspaceAuthorization} from "../context/WorkspaceAuthorizationContext";

const labels={REQUESTED:"Waiting for creator approval.",DECLINED:"Creator declined this request.",REVOKED:"Creator revoked access.",EXPIRED:"Insight access expired."};
const retryable=new Set(["DECLINED","REVOKED","EXPIRED"]);
const metricFields=[["Views","views"],["Reach","reach"],["Likes","likes"],["Comments","comments"],["Saves","saves"],["Shares","shares"],["Total interactions","totalInteractions"],["Average watch time","averageWatchTime"],["Total watch time","totalWatchTime"]];

export default function DeliverableInsightSharing({workspaceId,campaignId,creatorProfileId,deliverableId,token,onUnauthorized,onNotice}){
 const {hasPermission}=useWorkspaceAuthorization(),canView=hasPermission("DELIVERABLE_VIEW"),canEdit=hasPermission("DELIVERABLE_EDIT");
 const [share,setShare]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{if(!canView)return;const c=new AbortController();setLoading(true);setError("");api.getDeliverableSharedInsights(workspaceId,campaignId,creatorProfileId,deliverableId,token,{signal:c.signal}).then(setShare).catch(e=>{if(e.name==="AbortError")return;if(e.status===400)setShare(null);else if(e.status===401)onUnauthorized();else setError(e.message)}).finally(()=>!c.signal.aborted&&setLoading(false));return()=>c.abort()},[workspaceId,campaignId,creatorProfileId,deliverableId,token,canView]);
 async function requestAccess(){if(!canEdit||busy)return;setBusy(true);setError("");try{setShare(await api.requestDeliverableInsightShare(workspaceId,campaignId,creatorProfileId,deliverableId,token));onNotice?.("Insight request sent to the creator.")}catch(e){if(e.status===401)onUnauthorized();else setError(e.message)}finally{setBusy(false)}}
 if(!canView)return null;const status=share?.status,snapshots=status==="APPROVED"?[...(share.snapshots||[])].sort((a,b)=>new Date(b.capturedAt)-new Date(a.capturedAt)):[];
 return <section className="mt-4 border-t border-panel-border pt-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><h5 className="text-sm font-semibold">Insight sharing</h5><p className="mt-1 text-xs text-text-secondary">Deliverable-scoped metrics shared only with creator consent.</p></div>{canEdit&&(!share||retryable.has(status))&&<button type="button" disabled={busy} onClick={requestAccess} className="rounded-lg border border-panel-border px-3 py-2 text-xs font-semibold disabled:opacity-50">{busy?"Requesting…":share?"Request again":"Request insights"}</button>}</div>{loading&&<p role="status" className="mt-3 text-xs text-text-secondary">Checking insight access…</p>}{error&&<p role="alert" className="mt-3 rounded-lg bg-red-500/10 p-3 text-xs text-red-300">{error}</p>}{!loading&&!error&&!share&&<p className="mt-3 text-xs text-text-secondary">Insights not requested.</p>}{!loading&&!error&&labels[status]&&<p className="mt-3 text-xs font-semibold text-text-secondary">{labels[status]}</p>}{status==="APPROVED"&&<div className="mt-4 space-y-3"><p className="text-xs font-semibold text-emerald-300">Creator-approved snapshots · Captured metrics, not live analytics.</p>{!snapshots.length?<p className="text-xs text-text-secondary">No snapshots are available yet.</p>:snapshots.map(snapshot=><article key={snapshot.id||snapshot.capturedAt} className="rounded-xl border border-panel-border bg-panel-light/50 p-4"><div className="flex flex-wrap justify-between gap-2 text-xs"><strong>Captured {snapshot.capturedAt?new Date(snapshot.capturedAt).toLocaleString():"date unavailable"}</strong>{snapshot.permalink&&<a href={snapshot.permalink} target="_blank" rel="noopener noreferrer" className="text-accent-secondary underline">View Instagram content</a>}</div><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3">{metricFields.filter(([,key])=>snapshot[key]!=null||snapshot.metrics?.[key]!=null).map(([label,key])=><div key={key} className="rounded-lg border border-panel-border p-2"><p className="text-[10px] text-text-secondary">{label}</p><p className="mt-1 font-mono text-sm font-semibold">{new Intl.NumberFormat().format(snapshot[key]??snapshot.metrics?.[key])}</p></div>)}</div></article>)}</div>}</section>;
}
