import { useEffect, useRef, useState } from "react";
import { DELIVERABLE_STATUSES, DELIVERABLE_STATUS_LABELS, DELIVERABLE_TYPES, DELIVERABLE_TYPE_LABELS } from "../deliverableTypes";

const empty = { type:"REEL", customType:"", quantity:1, dueDate:"", status:"PLANNED", submissionUrl:"", publishedUrl:"", usageRightsStart:"", usageRightsEnd:"", internalFeedback:"", revisionNotes:"" };
const fieldClass = "mt-1 w-full rounded-xl border border-panel-border bg-bg-deep p-3 text-text-primary";
const isHttpUrl = value => { try { const url = new URL(value); return url.protocol === "http:" || url.protocol === "https:"; } catch { return false; } };

export default function DeliverableForm({initial,onSubmit,onCancel,submitting}){
 const [form,setForm]=useState(()=>({...empty,...initial,customType:initial?.customType||"",dueDate:initial?.dueDate||"",submissionUrl:initial?.submissionUrl||"",publishedUrl:initial?.publishedUrl||"",usageRightsStart:initial?.usageRightsStart||"",usageRightsEnd:initial?.usageRightsEnd||"",internalFeedback:initial?.internalFeedback||"",revisionNotes:initial?.revisionNotes||""}));
 const [error,setError]=useState(null);const first=useRef(null);const dialog=useRef(null);
 useEffect(()=>{const previous=document.activeElement;first.current?.focus();const keydown=e=>{if(e.key==="Escape")onCancel();if(e.key!=="Tab")return;const controls=[...dialog.current.querySelectorAll('button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled])')];if(!controls.length)return;const firstControl=controls[0],lastControl=controls[controls.length-1];if(e.shiftKey&&document.activeElement===firstControl){e.preventDefault();lastControl.focus()}else if(!e.shiftKey&&document.activeElement===lastControl){e.preventDefault();firstControl.focus()}};document.addEventListener("keydown",keydown);return()=>{document.removeEventListener("keydown",keydown);previous?.focus?.()}},[]);
 const set=(name,value)=>setForm(f=>({...f,[name]:value,...(name==="type"&&value!=="OTHER"?{customType:""}:{})}));
 async function save(e){e.preventDefault();setError(null);if(form.type==="OTHER"&&!form.customType.trim())return setError("Custom type is required for Other.");if(form.quantity<1||form.quantity>100)return setError("Quantity must be between 1 and 100.");for(const [label,value] of [["Submission URL",form.submissionUrl],["Published URL",form.publishedUrl]])if(value&&!isHttpUrl(value))return setError(`${label} must be a valid HTTP or HTTPS URL.`);if(form.usageRightsStart&&form.usageRightsEnd&&form.usageRightsEnd<form.usageRightsStart)return setError("Usage-rights end date cannot be before the start date.");
  const payload={type:form.type,quantity:Number(form.quantity),status:form.status};if(form.type==="OTHER")payload.customType=form.customType.trim();
  if(initial){for(const name of ["dueDate","usageRightsStart","usageRightsEnd"]){if(form[name])payload[name]=form[name];else if(initial[name])payload[`clear${name[0].toUpperCase()}${name.slice(1)}`]=true}for(const name of ["submissionUrl","publishedUrl","internalFeedback","revisionNotes"])payload[name]=form[name].trim();}
  else {for(const name of ["dueDate","submissionUrl","publishedUrl","usageRightsStart","usageRightsEnd","internalFeedback","revisionNotes"])payload[name]=form[name].trim()||null;}
  try{await onSubmit(payload)}catch(err){setError(err.message)}
 }
 const warning=form.status==="SUBMITTED"&&!form.submissionUrl?"A submission URL has not been added.":form.status==="REVISION_REQUESTED"&&!form.revisionNotes?"Revision notes have not been added.":form.status==="PUBLISHED"&&!form.publishedUrl?"A published-content URL has not been added.":null;
 return <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/75 p-4"><div ref={dialog} role="dialog" aria-modal="true" aria-labelledby="deliverable-form-title" className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-3xl bg-panel p-6"><div className="flex justify-between gap-4"><div><h2 id="deliverable-form-title" className="text-lg font-bold">{initial?"Edit deliverable":"Create deliverable"}</h2><p className="mt-1 text-xs text-text-secondary">Track content, review, publication, and usage rights.</p></div><button type="button" aria-label="Close deliverable form" onClick={onCancel}>✕</button></div><form onSubmit={save} className="mt-6 space-y-6">
 <fieldset className="grid gap-3 sm:grid-cols-2"><legend className="mb-2 font-semibold">1. Deliverable details</legend><label className="text-xs text-text-secondary">Type<select ref={first} value={form.type} onChange={e=>set("type",e.target.value)} className={fieldClass}>{DELIVERABLE_TYPES.map(x=><option key={x} value={x}>{DELIVERABLE_TYPE_LABELS[x]}</option>)}</select></label>{form.type==="OTHER"&&<label className="text-xs text-text-secondary">Custom type<input required maxLength={120} value={form.customType} onChange={e=>set("customType",e.target.value)} className={fieldClass}/></label>}<label className="text-xs text-text-secondary">Quantity<input required type="number" min="1" max="100" value={form.quantity} onChange={e=>set("quantity",e.target.value)} className={fieldClass}/></label></fieldset>
 <fieldset className="grid gap-3 sm:grid-cols-2"><legend className="mb-2 font-semibold">2. Schedule and status</legend><label className="text-xs text-text-secondary">Due date<input type="date" value={form.dueDate} onChange={e=>set("dueDate",e.target.value)} className={fieldClass}/></label><label className="text-xs text-text-secondary">Status<select value={form.status} onChange={e=>set("status",e.target.value)} className={fieldClass}>{DELIVERABLE_STATUSES.map(x=><option key={x} value={x}>{DELIVERABLE_STATUS_LABELS[x]}</option>)}</select></label></fieldset>
 <fieldset className="grid gap-3 sm:grid-cols-2"><legend className="mb-2 font-semibold">3. Submission and publishing</legend><label className="text-xs text-text-secondary">Submission URL<input type="url" maxLength={2048} value={form.submissionUrl} onChange={e=>set("submissionUrl",e.target.value)} className={fieldClass}/></label><label className="text-xs text-text-secondary">Published-content URL<input type="url" maxLength={2048} value={form.publishedUrl} onChange={e=>set("publishedUrl",e.target.value)} className={fieldClass}/></label>{warning&&<p className="text-xs text-amber-300 sm:col-span-2">{warning} You can still save.</p>}</fieldset>
 <fieldset className="grid gap-3 sm:grid-cols-2"><legend className="mb-2 font-semibold">4. Usage rights</legend><label className="text-xs text-text-secondary">Start date<input type="date" value={form.usageRightsStart} onChange={e=>set("usageRightsStart",e.target.value)} className={fieldClass}/></label><label className="text-xs text-text-secondary">End date<input type="date" value={form.usageRightsEnd} onChange={e=>set("usageRightsEnd",e.target.value)} className={fieldClass}/></label></fieldset>
 <fieldset className="grid gap-3 sm:grid-cols-2"><legend className="mb-2 font-semibold">5. Internal review</legend><label className="text-xs text-text-secondary">Internal feedback<textarea rows="3" maxLength={4000} value={form.internalFeedback} onChange={e=>set("internalFeedback",e.target.value)} className={fieldClass}/></label><label className="text-xs text-text-secondary">Revision notes<textarea rows="3" maxLength={4000} value={form.revisionNotes} onChange={e=>set("revisionNotes",e.target.value)} className={fieldClass}/></label></fieldset>
 {error&&<p role="alert" className="rounded-xl bg-red-500/10 p-3 text-sm text-red-300">{error}</p>}<div className="flex gap-2"><button disabled={submitting} className="rounded-xl bg-accent-primary px-5 py-3 text-sm disabled:opacity-50">{submitting?"Saving…":"Save deliverable"}</button><button type="button" disabled={submitting} onClick={onCancel} className="rounded-xl border border-panel-border px-5 py-3 text-sm">Cancel</button></div></form></div></div>;
}
